# Generated by Django 5.1.2 on 2024-10-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_members_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
